name: Continuous integration

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  versioning:
    # Skip the job if it's not running in the `neuroglia-io/TestCICD` repo
    if: github.repository == '0nary/TestCICD' && github.ref_name == 'main'
    uses: ./.github/workflows/versioning.yml
    secrets: inherit

  build:
    needs: [versioning]
    uses: ./.github/workflows/build-dotnet.yml
    secrets: inherit

  release:
    needs: [build]
    uses: ./.github/workflows/release.yml
    secrets: inherit
